Romaji2Kanji = {
"01AbeShyogo":"阿部　匠悟　",
"02IkedaMasako":"池田　真佐子",
"03ItoKyoko":"伊藤　匡子　",
"04ImaiKenta":"今井　健太　",
"05EzakiYuuya":"江﨑　友哉　",
"06OshimaNaomi":"大島　尚美　",
"07TakeshitaKohei":"竹下　浩平　",
"08KagayaShyunsuke":"加賀谷　俊介",
"09KasugaJyunpei":"春日　純平　",
"10KawaguchiRyota":"川口　量太　",
"11KandaurovaMaria":"Kandaurova Maria",
"12KoshimuraTaichi":"越村　太一　",
"13ShimadaFumiya":"島田　郁也　",
"14ShimadaYo":"嶋田　曜　　",
"15SuenagaHideyasu":"末永　英保　",
"16TakataMasaki":"髙田　雅喜　",
"17TamuraJyunpei":"田村　純平　",
"18TomimuraKeiko":"富村　恵子　",
"19DoiTakumi":"土井　匠海　",
"20NakazawaHiromi":"中澤　ひろみ",
"21NakataKensuke":"中田　健介　",
"22HidakaTakumi":"日髙　卓見　",
"23HirotaSaki":"廣田　早紀　",
"24HoriTakahide":"堀　　孝秀　",
"25MachidaKoichi":"町田　浩一　",
"26MatsumotoRyosuke":"松本　亮介　",
}